name: StackHolderAPI
version: '${project.version}'
main: me.higherlevel.stackholderapi.StackHolderAPI
api-version: '1.20'
depend: [StackAPI]
description: A plugin for easily creating and keeping track of new inventories.